server:
  port: 8080
spring:
  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Be0101
jwt:
  secret-key-source: ${JWT_SECRET_KEY}  #{JWT_SECRET_KEY} = super-coding 환경설정에 해놓았음